org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.4.21
forge_version_range=[47.4.21,48)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=t2me
mod_name=T2ME - Threaded Task Management Engine
mod_license=MIT
mod_version=0.2.0-dev.1
mod_group_id=dev.t2me
mod_authors=MimoAlexer and T2ME contributors
mod_description=An experimental high-throughput, stage-aware threaded chunk engine and pregenerator for Minecraft Forge 1.20.1.
